#include "unicorn/core.hpp"
#include "unicorn/character.hpp"
#include "unicorn/string.hpp"
#include "unicorn/utf.hpp"
#include "prion/unit-test.hpp"
#include <string>
#include <vector>

using namespace std::literals;
using namespace Unicorn;

namespace {

    void check_fix_left() {

        u8string s8;
        u16string s16;
        u32string s32;

        TEST_EQUAL(str_fix_left(""s, 0), "");
        TEST_EQUAL(str_fix_left(""s, 1), " ");
        TEST_EQUAL(str_fix_left(""s, 2), "  ");
        TEST_EQUAL(str_fix_left(""s, 0, U'*'), "");
        TEST_EQUAL(str_fix_left(""s, 1, U'*'), "*");
        TEST_EQUAL(str_fix_left(""s, 2, U'*'), "**");
        TEST_EQUAL(str_fix_left(""s, 0, U'§'), "");
        TEST_EQUAL(str_fix_left(""s, 1, U'§'), "§");
        TEST_EQUAL(str_fix_left(""s, 2, U'§'), "§§");
        TEST_EQUAL(str_fix_left("Hello"s, 0), "");
        TEST_EQUAL(str_fix_left("Hello"s, 4), "Hell");
        TEST_EQUAL(str_fix_left("Hello"s, 5), "Hello");
        TEST_EQUAL(str_fix_left("Hello"s, 6), "Hello ");
        TEST_EQUAL(str_fix_left("Hello"s, 7), "Hello  ");
        TEST_EQUAL(str_fix_left("Hello"s, 0, U'*'), "");
        TEST_EQUAL(str_fix_left("Hello"s, 4, U'*'), "Hell");
        TEST_EQUAL(str_fix_left("Hello"s, 5, U'*'), "Hello");
        TEST_EQUAL(str_fix_left("Hello"s, 6, U'*'), "Hello*");
        TEST_EQUAL(str_fix_left("Hello"s, 7, U'*'), "Hello**");
        TEST_EQUAL(str_fix_left("Hello"s, 0, U'§'), "");
        TEST_EQUAL(str_fix_left("Hello"s, 4, U'§'), "Hell");
        TEST_EQUAL(str_fix_left("Hello"s, 5, U'§'), "Hello");
        TEST_EQUAL(str_fix_left("Hello"s, 6, U'§'), "Hello§");
        TEST_EQUAL(str_fix_left("Hello"s, 7, U'§'), "Hello§§");

        TEST_EQUAL(str_fix_left(u""s, 0), u"");
        TEST_EQUAL(str_fix_left(u""s, 1), u" ");
        TEST_EQUAL(str_fix_left(u""s, 2), u"  ");
        TEST_EQUAL(str_fix_left(u""s, 0, U'*'), u"");
        TEST_EQUAL(str_fix_left(u""s, 1, U'*'), u"*");
        TEST_EQUAL(str_fix_left(u""s, 2, U'*'), u"**");
        TEST_EQUAL(str_fix_left(u""s, 0, U'§'), u"");
        TEST_EQUAL(str_fix_left(u""s, 1, U'§'), u"§");
        TEST_EQUAL(str_fix_left(u""s, 2, U'§'), u"§§");
        TEST_EQUAL(str_fix_left(u"Hello"s, 0), u"");
        TEST_EQUAL(str_fix_left(u"Hello"s, 4), u"Hell");
        TEST_EQUAL(str_fix_left(u"Hello"s, 5), u"Hello");
        TEST_EQUAL(str_fix_left(u"Hello"s, 6), u"Hello ");
        TEST_EQUAL(str_fix_left(u"Hello"s, 7), u"Hello  ");
        TEST_EQUAL(str_fix_left(u"Hello"s, 0, U'*'), u"");
        TEST_EQUAL(str_fix_left(u"Hello"s, 4, U'*'), u"Hell");
        TEST_EQUAL(str_fix_left(u"Hello"s, 5, U'*'), u"Hello");
        TEST_EQUAL(str_fix_left(u"Hello"s, 6, U'*'), u"Hello*");
        TEST_EQUAL(str_fix_left(u"Hello"s, 7, U'*'), u"Hello**");
        TEST_EQUAL(str_fix_left(u"Hello"s, 0, U'§'), u"");
        TEST_EQUAL(str_fix_left(u"Hello"s, 4, U'§'), u"Hell");
        TEST_EQUAL(str_fix_left(u"Hello"s, 5, U'§'), u"Hello");
        TEST_EQUAL(str_fix_left(u"Hello"s, 6, U'§'), u"Hello§");
        TEST_EQUAL(str_fix_left(u"Hello"s, 7, U'§'), u"Hello§§");

        TEST_EQUAL(str_fix_left(U""s, 0), U"");
        TEST_EQUAL(str_fix_left(U""s, 1), U" ");
        TEST_EQUAL(str_fix_left(U""s, 2), U"  ");
        TEST_EQUAL(str_fix_left(U""s, 0, U'*'), U"");
        TEST_EQUAL(str_fix_left(U""s, 1, U'*'), U"*");
        TEST_EQUAL(str_fix_left(U""s, 2, U'*'), U"**");
        TEST_EQUAL(str_fix_left(U""s, 0, U'§'), U"");
        TEST_EQUAL(str_fix_left(U""s, 1, U'§'), U"§");
        TEST_EQUAL(str_fix_left(U""s, 2, U'§'), U"§§");
        TEST_EQUAL(str_fix_left(U"Hello"s, 0), U"");
        TEST_EQUAL(str_fix_left(U"Hello"s, 4), U"Hell");
        TEST_EQUAL(str_fix_left(U"Hello"s, 5), U"Hello");
        TEST_EQUAL(str_fix_left(U"Hello"s, 6), U"Hello ");
        TEST_EQUAL(str_fix_left(U"Hello"s, 7), U"Hello  ");
        TEST_EQUAL(str_fix_left(U"Hello"s, 0, U'*'), U"");
        TEST_EQUAL(str_fix_left(U"Hello"s, 4, U'*'), U"Hell");
        TEST_EQUAL(str_fix_left(U"Hello"s, 5, U'*'), U"Hello");
        TEST_EQUAL(str_fix_left(U"Hello"s, 6, U'*'), U"Hello*");
        TEST_EQUAL(str_fix_left(U"Hello"s, 7, U'*'), U"Hello**");
        TEST_EQUAL(str_fix_left(U"Hello"s, 0, U'§'), U"");
        TEST_EQUAL(str_fix_left(U"Hello"s, 4, U'§'), U"Hell");
        TEST_EQUAL(str_fix_left(U"Hello"s, 5, U'§'), U"Hello");
        TEST_EQUAL(str_fix_left(U"Hello"s, 6, U'§'), U"Hello§");
        TEST_EQUAL(str_fix_left(U"Hello"s, 7, U'§'), U"Hello§§");

        s8 = u8"";       TRY(str_fix_left_in(s8, 0));        TEST_EQUAL(s8, u8"");
        s8 = u8"";       TRY(str_fix_left_in(s8, 1));        TEST_EQUAL(s8, u8" ");
        s8 = u8"";       TRY(str_fix_left_in(s8, 2));        TEST_EQUAL(s8, u8"  ");
        s8 = u8"";       TRY(str_fix_left_in(s8, 0, U'*'));  TEST_EQUAL(s8, u8"");
        s8 = u8"";       TRY(str_fix_left_in(s8, 1, U'*'));  TEST_EQUAL(s8, u8"*");
        s8 = u8"";       TRY(str_fix_left_in(s8, 2, U'*'));  TEST_EQUAL(s8, u8"**");
        s8 = u8"";       TRY(str_fix_left_in(s8, 0, U'§'));  TEST_EQUAL(s8, u8"");
        s8 = u8"";       TRY(str_fix_left_in(s8, 1, U'§'));  TEST_EQUAL(s8, u8"§");
        s8 = u8"";       TRY(str_fix_left_in(s8, 2, U'§'));  TEST_EQUAL(s8, u8"§§");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 0));        TEST_EQUAL(s8, u8"");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 4));        TEST_EQUAL(s8, u8"Hell");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 5));        TEST_EQUAL(s8, u8"Hello");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 6));        TEST_EQUAL(s8, u8"Hello ");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 7));        TEST_EQUAL(s8, u8"Hello  ");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 0, U'*'));  TEST_EQUAL(s8, u8"");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 4, U'*'));  TEST_EQUAL(s8, u8"Hell");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 5, U'*'));  TEST_EQUAL(s8, u8"Hello");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 6, U'*'));  TEST_EQUAL(s8, u8"Hello*");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 7, U'*'));  TEST_EQUAL(s8, u8"Hello**");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 0, U'§'));  TEST_EQUAL(s8, u8"");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 4, U'§'));  TEST_EQUAL(s8, u8"Hell");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 5, U'§'));  TEST_EQUAL(s8, u8"Hello");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 6, U'§'));  TEST_EQUAL(s8, u8"Hello§");
        s8 = u8"Hello";  TRY(str_fix_left_in(s8, 7, U'§'));  TEST_EQUAL(s8, u8"Hello§§");

        s16 = u"";       TRY(str_fix_left_in(s16, 0));        TEST_EQUAL(s16, u"");
        s16 = u"";       TRY(str_fix_left_in(s16, 1));        TEST_EQUAL(s16, u" ");
        s16 = u"";       TRY(str_fix_left_in(s16, 2));        TEST_EQUAL(s16, u"  ");
        s16 = u"";       TRY(str_fix_left_in(s16, 0, U'*'));  TEST_EQUAL(s16, u"");
        s16 = u"";       TRY(str_fix_left_in(s16, 1, U'*'));  TEST_EQUAL(s16, u"*");
        s16 = u"";       TRY(str_fix_left_in(s16, 2, U'*'));  TEST_EQUAL(s16, u"**");
        s16 = u"";       TRY(str_fix_left_in(s16, 0, U'§'));  TEST_EQUAL(s16, u"");
        s16 = u"";       TRY(str_fix_left_in(s16, 1, U'§'));  TEST_EQUAL(s16, u"§");
        s16 = u"";       TRY(str_fix_left_in(s16, 2, U'§'));  TEST_EQUAL(s16, u"§§");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 0));        TEST_EQUAL(s16, u"");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 4));        TEST_EQUAL(s16, u"Hell");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 5));        TEST_EQUAL(s16, u"Hello");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 6));        TEST_EQUAL(s16, u"Hello ");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 7));        TEST_EQUAL(s16, u"Hello  ");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 0, U'*'));  TEST_EQUAL(s16, u"");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 4, U'*'));  TEST_EQUAL(s16, u"Hell");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 5, U'*'));  TEST_EQUAL(s16, u"Hello");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 6, U'*'));  TEST_EQUAL(s16, u"Hello*");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 7, U'*'));  TEST_EQUAL(s16, u"Hello**");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 0, U'§'));  TEST_EQUAL(s16, u"");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 4, U'§'));  TEST_EQUAL(s16, u"Hell");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 5, U'§'));  TEST_EQUAL(s16, u"Hello");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 6, U'§'));  TEST_EQUAL(s16, u"Hello§");
        s16 = u"Hello";  TRY(str_fix_left_in(s16, 7, U'§'));  TEST_EQUAL(s16, u"Hello§§");

        s32 = U"";       TRY(str_fix_left_in(s32, 0));        TEST_EQUAL(s32, U"");
        s32 = U"";       TRY(str_fix_left_in(s32, 1));        TEST_EQUAL(s32, U" ");
        s32 = U"";       TRY(str_fix_left_in(s32, 2));        TEST_EQUAL(s32, U"  ");
        s32 = U"";       TRY(str_fix_left_in(s32, 0, U'*'));  TEST_EQUAL(s32, U"");
        s32 = U"";       TRY(str_fix_left_in(s32, 1, U'*'));  TEST_EQUAL(s32, U"*");
        s32 = U"";       TRY(str_fix_left_in(s32, 2, U'*'));  TEST_EQUAL(s32, U"**");
        s32 = U"";       TRY(str_fix_left_in(s32, 0, U'§'));  TEST_EQUAL(s32, U"");
        s32 = U"";       TRY(str_fix_left_in(s32, 1, U'§'));  TEST_EQUAL(s32, U"§");
        s32 = U"";       TRY(str_fix_left_in(s32, 2, U'§'));  TEST_EQUAL(s32, U"§§");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 0));        TEST_EQUAL(s32, U"");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 4));        TEST_EQUAL(s32, U"Hell");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 5));        TEST_EQUAL(s32, U"Hello");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 6));        TEST_EQUAL(s32, U"Hello ");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 7));        TEST_EQUAL(s32, U"Hello  ");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 0, U'*'));  TEST_EQUAL(s32, U"");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 4, U'*'));  TEST_EQUAL(s32, U"Hell");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 5, U'*'));  TEST_EQUAL(s32, U"Hello");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 6, U'*'));  TEST_EQUAL(s32, U"Hello*");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 7, U'*'));  TEST_EQUAL(s32, U"Hello**");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 0, U'§'));  TEST_EQUAL(s32, U"");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 4, U'§'));  TEST_EQUAL(s32, U"Hell");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 5, U'§'));  TEST_EQUAL(s32, U"Hello");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 6, U'§'));  TEST_EQUAL(s32, U"Hello§");
        s32 = U"Hello";  TRY(str_fix_left_in(s32, 7, U'§'));  TEST_EQUAL(s32, U"Hello§§");

    }

    void check_fix_right() {

        u8string s8;
        u16string s16;
        u32string s32;

        TEST_EQUAL(str_fix_right(""s, 0), "");
        TEST_EQUAL(str_fix_right(""s, 1), " ");
        TEST_EQUAL(str_fix_right(""s, 2), "  ");
        TEST_EQUAL(str_fix_right(""s, 0, U'*'), "");
        TEST_EQUAL(str_fix_right(""s, 1, U'*'), "*");
        TEST_EQUAL(str_fix_right(""s, 2, U'*'), "**");
        TEST_EQUAL(str_fix_right(""s, 0, U'§'), "");
        TEST_EQUAL(str_fix_right(""s, 1, U'§'), "§");
        TEST_EQUAL(str_fix_right(""s, 2, U'§'), "§§");
        TEST_EQUAL(str_fix_right("Hello"s, 0), "");
        TEST_EQUAL(str_fix_right("Hello"s, 4), "ello");
        TEST_EQUAL(str_fix_right("Hello"s, 5), "Hello");
        TEST_EQUAL(str_fix_right("Hello"s, 6), " Hello");
        TEST_EQUAL(str_fix_right("Hello"s, 7), "  Hello");
        TEST_EQUAL(str_fix_right("Hello"s, 0, U'*'), "");
        TEST_EQUAL(str_fix_right("Hello"s, 4, U'*'), "ello");
        TEST_EQUAL(str_fix_right("Hello"s, 5, U'*'), "Hello");
        TEST_EQUAL(str_fix_right("Hello"s, 6, U'*'), "*Hello");
        TEST_EQUAL(str_fix_right("Hello"s, 7, U'*'), "**Hello");
        TEST_EQUAL(str_fix_right("Hello"s, 0, U'§'), "");
        TEST_EQUAL(str_fix_right("Hello"s, 4, U'§'), "ello");
        TEST_EQUAL(str_fix_right("Hello"s, 5, U'§'), "Hello");
        TEST_EQUAL(str_fix_right("Hello"s, 6, U'§'), "§Hello");
        TEST_EQUAL(str_fix_right("Hello"s, 7, U'§'), "§§Hello");

        TEST_EQUAL(str_fix_right(u""s, 0), u"");
        TEST_EQUAL(str_fix_right(u""s, 1), u" ");
        TEST_EQUAL(str_fix_right(u""s, 2), u"  ");
        TEST_EQUAL(str_fix_right(u""s, 0, U'*'), u"");
        TEST_EQUAL(str_fix_right(u""s, 1, U'*'), u"*");
        TEST_EQUAL(str_fix_right(u""s, 2, U'*'), u"**");
        TEST_EQUAL(str_fix_right(u""s, 0, U'§'), u"");
        TEST_EQUAL(str_fix_right(u""s, 1, U'§'), u"§");
        TEST_EQUAL(str_fix_right(u""s, 2, U'§'), u"§§");
        TEST_EQUAL(str_fix_right(u"Hello"s, 0), u"");
        TEST_EQUAL(str_fix_right(u"Hello"s, 4), u"ello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 5), u"Hello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 6), u" Hello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 7), u"  Hello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 0, U'*'), u"");
        TEST_EQUAL(str_fix_right(u"Hello"s, 4, U'*'), u"ello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 5, U'*'), u"Hello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 6, U'*'), u"*Hello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 7, U'*'), u"**Hello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 0, U'§'), u"");
        TEST_EQUAL(str_fix_right(u"Hello"s, 4, U'§'), u"ello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 5, U'§'), u"Hello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 6, U'§'), u"§Hello");
        TEST_EQUAL(str_fix_right(u"Hello"s, 7, U'§'), u"§§Hello");

        TEST_EQUAL(str_fix_right(U""s, 0), U"");
        TEST_EQUAL(str_fix_right(U""s, 1), U" ");
        TEST_EQUAL(str_fix_right(U""s, 2), U"  ");
        TEST_EQUAL(str_fix_right(U""s, 0, U'*'), U"");
        TEST_EQUAL(str_fix_right(U""s, 1, U'*'), U"*");
        TEST_EQUAL(str_fix_right(U""s, 2, U'*'), U"**");
        TEST_EQUAL(str_fix_right(U""s, 0, U'§'), U"");
        TEST_EQUAL(str_fix_right(U""s, 1, U'§'), U"§");
        TEST_EQUAL(str_fix_right(U""s, 2, U'§'), U"§§");
        TEST_EQUAL(str_fix_right(U"Hello"s, 0), U"");
        TEST_EQUAL(str_fix_right(U"Hello"s, 4), U"ello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 5), U"Hello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 6), U" Hello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 7), U"  Hello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 0, U'*'), U"");
        TEST_EQUAL(str_fix_right(U"Hello"s, 4, U'*'), U"ello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 5, U'*'), U"Hello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 6, U'*'), U"*Hello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 7, U'*'), U"**Hello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 0, U'§'), U"");
        TEST_EQUAL(str_fix_right(U"Hello"s, 4, U'§'), U"ello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 5, U'§'), U"Hello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 6, U'§'), U"§Hello");
        TEST_EQUAL(str_fix_right(U"Hello"s, 7, U'§'), U"§§Hello");

        s8 = u8"";       TRY(str_fix_right_in(s8, 0));        TEST_EQUAL(s8, u8"");
        s8 = u8"";       TRY(str_fix_right_in(s8, 1));        TEST_EQUAL(s8, u8" ");
        s8 = u8"";       TRY(str_fix_right_in(s8, 2));        TEST_EQUAL(s8, u8"  ");
        s8 = u8"";       TRY(str_fix_right_in(s8, 0, U'*'));  TEST_EQUAL(s8, u8"");
        s8 = u8"";       TRY(str_fix_right_in(s8, 1, U'*'));  TEST_EQUAL(s8, u8"*");
        s8 = u8"";       TRY(str_fix_right_in(s8, 2, U'*'));  TEST_EQUAL(s8, u8"**");
        s8 = u8"";       TRY(str_fix_right_in(s8, 0, U'§'));  TEST_EQUAL(s8, u8"");
        s8 = u8"";       TRY(str_fix_right_in(s8, 1, U'§'));  TEST_EQUAL(s8, u8"§");
        s8 = u8"";       TRY(str_fix_right_in(s8, 2, U'§'));  TEST_EQUAL(s8, u8"§§");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 0));        TEST_EQUAL(s8, u8"");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 4));        TEST_EQUAL(s8, u8"ello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 5));        TEST_EQUAL(s8, u8"Hello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 6));        TEST_EQUAL(s8, u8" Hello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 7));        TEST_EQUAL(s8, u8"  Hello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 0, U'*'));  TEST_EQUAL(s8, u8"");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 4, U'*'));  TEST_EQUAL(s8, u8"ello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 5, U'*'));  TEST_EQUAL(s8, u8"Hello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 6, U'*'));  TEST_EQUAL(s8, u8"*Hello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 7, U'*'));  TEST_EQUAL(s8, u8"**Hello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 0, U'§'));  TEST_EQUAL(s8, u8"");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 4, U'§'));  TEST_EQUAL(s8, u8"ello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 5, U'§'));  TEST_EQUAL(s8, u8"Hello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 6, U'§'));  TEST_EQUAL(s8, u8"§Hello");
        s8 = u8"Hello";  TRY(str_fix_right_in(s8, 7, U'§'));  TEST_EQUAL(s8, u8"§§Hello");

        s16 = u"";       TRY(str_fix_right_in(s16, 0));        TEST_EQUAL(s16, u"");
        s16 = u"";       TRY(str_fix_right_in(s16, 1));        TEST_EQUAL(s16, u" ");
        s16 = u"";       TRY(str_fix_right_in(s16, 2));        TEST_EQUAL(s16, u"  ");
        s16 = u"";       TRY(str_fix_right_in(s16, 0, U'*'));  TEST_EQUAL(s16, u"");
        s16 = u"";       TRY(str_fix_right_in(s16, 1, U'*'));  TEST_EQUAL(s16, u"*");
        s16 = u"";       TRY(str_fix_right_in(s16, 2, U'*'));  TEST_EQUAL(s16, u"**");
        s16 = u"";       TRY(str_fix_right_in(s16, 0, U'§'));  TEST_EQUAL(s16, u"");
        s16 = u"";       TRY(str_fix_right_in(s16, 1, U'§'));  TEST_EQUAL(s16, u"§");
        s16 = u"";       TRY(str_fix_right_in(s16, 2, U'§'));  TEST_EQUAL(s16, u"§§");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 0));        TEST_EQUAL(s16, u"");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 4));        TEST_EQUAL(s16, u"ello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 5));        TEST_EQUAL(s16, u"Hello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 6));        TEST_EQUAL(s16, u" Hello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 7));        TEST_EQUAL(s16, u"  Hello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 0, U'*'));  TEST_EQUAL(s16, u"");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 4, U'*'));  TEST_EQUAL(s16, u"ello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 5, U'*'));  TEST_EQUAL(s16, u"Hello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 6, U'*'));  TEST_EQUAL(s16, u"*Hello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 7, U'*'));  TEST_EQUAL(s16, u"**Hello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 0, U'§'));  TEST_EQUAL(s16, u"");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 4, U'§'));  TEST_EQUAL(s16, u"ello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 5, U'§'));  TEST_EQUAL(s16, u"Hello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 6, U'§'));  TEST_EQUAL(s16, u"§Hello");
        s16 = u"Hello";  TRY(str_fix_right_in(s16, 7, U'§'));  TEST_EQUAL(s16, u"§§Hello");

        s32 = U"";       TRY(str_fix_right_in(s32, 0));        TEST_EQUAL(s32, U"");
        s32 = U"";       TRY(str_fix_right_in(s32, 1));        TEST_EQUAL(s32, U" ");
        s32 = U"";       TRY(str_fix_right_in(s32, 2));        TEST_EQUAL(s32, U"  ");
        s32 = U"";       TRY(str_fix_right_in(s32, 0, U'*'));  TEST_EQUAL(s32, U"");
        s32 = U"";       TRY(str_fix_right_in(s32, 1, U'*'));  TEST_EQUAL(s32, U"*");
        s32 = U"";       TRY(str_fix_right_in(s32, 2, U'*'));  TEST_EQUAL(s32, U"**");
        s32 = U"";       TRY(str_fix_right_in(s32, 0, U'§'));  TEST_EQUAL(s32, U"");
        s32 = U"";       TRY(str_fix_right_in(s32, 1, U'§'));  TEST_EQUAL(s32, U"§");
        s32 = U"";       TRY(str_fix_right_in(s32, 2, U'§'));  TEST_EQUAL(s32, U"§§");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 0));        TEST_EQUAL(s32, U"");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 4));        TEST_EQUAL(s32, U"ello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 5));        TEST_EQUAL(s32, U"Hello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 6));        TEST_EQUAL(s32, U" Hello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 7));        TEST_EQUAL(s32, U"  Hello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 0, U'*'));  TEST_EQUAL(s32, U"");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 4, U'*'));  TEST_EQUAL(s32, U"ello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 5, U'*'));  TEST_EQUAL(s32, U"Hello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 6, U'*'));  TEST_EQUAL(s32, U"*Hello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 7, U'*'));  TEST_EQUAL(s32, U"**Hello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 0, U'§'));  TEST_EQUAL(s32, U"");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 4, U'§'));  TEST_EQUAL(s32, U"ello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 5, U'§'));  TEST_EQUAL(s32, U"Hello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 6, U'§'));  TEST_EQUAL(s32, U"§Hello");
        s32 = U"Hello";  TRY(str_fix_right_in(s32, 7, U'§'));  TEST_EQUAL(s32, U"§§Hello");

    }

    void check_insert() {

        u8string s8, t8;
        u16string s16, t16;
        u32string s32, t32;
        Utf8Iterator i8, j8;
        Utf16Iterator i16, j16;
        Utf32Iterator i32, j32;

        s8 = u8"Hello world";
        t8 = u8"€urope";
        TRY(i8 = j8 = utf_begin(s8));
        TRY(std::advance(j8, 5));
        TEST_EQUAL(str_insert(i8, j8, t8), u8"€urope world");
        TEST_EQUAL(str_insert(irange(i8, j8), utf_range(t8)), u8"€urope world");
        TRY(i8 = utf_begin(s8));
        TRY(j8 = utf_end(s8));
        TRY(std::advance(i8, 6));
        TEST_EQUAL(str_insert(i8, j8, t8), u8"Hello €urope");
        TEST_EQUAL(str_insert(irange(i8, j8), utf_range(t8)), u8"Hello €urope");
        TEST_EQUAL(str_insert(i8, i8, t8), u8"Hello €uropeworld");
        TEST_EQUAL(str_insert(irange(i8, i8), utf_range(t8)), u8"Hello €uropeworld");
        TEST_EQUAL(str_insert(utf_range(s8), t8), u8"€urope");
        TEST_EQUAL(str_insert(utf_range(s8), utf_range(t8)), u8"€urope");
        s8 = u8"Hello world";
        TRY(i8 = j8 = utf_begin(s8));
        TRY(std::advance(j8, 5));
        TEST_EQUAL(u_str(str_insert_in(s8, i8, j8, t8)), u8"€urope");
        TEST_EQUAL(s8, u8"€urope world");
        s8 = u8"Hello world";
        TRY(i8 = j8 = utf_begin(s8));
        TRY(std::advance(j8, 5));
        TEST_EQUAL(u_str(str_insert_in(s8, irange(i8, j8), utf_range(t8))), u8"€urope");
        TEST_EQUAL(s8, u8"€urope world");
        s8 = u8"Hello world";
        TRY(i8 = utf_begin(s8));
        TRY(j8 = utf_end(s8));
        TRY(std::advance(i8, 6));
        TEST_EQUAL(u_str(str_insert_in(s8, i8, j8, t8)), u8"€urope");
        TEST_EQUAL(s8, u8"Hello €urope");
        s8 = u8"Hello world";
        TRY(i8 = utf_begin(s8));
        TRY(j8 = utf_end(s8));
        TRY(std::advance(i8, 6));
        TEST_EQUAL(u_str(str_insert_in(s8, irange(i8, j8), utf_range(t8))), u8"€urope");
        TEST_EQUAL(s8, u8"Hello €urope");
        s8 = u8"Hello world";
        TRY(i8 = utf_begin(s8));
        TRY(j8 = utf_end(s8));
        TRY(std::advance(i8, 6));
        TEST_EQUAL(u_str(str_insert_in(s8, i8, t8)), u8"€urope");
        TEST_EQUAL(s8, u8"Hello €uropeworld");
        s8 = u8"Hello world";
        TRY(i8 = utf_begin(s8));
        TRY(j8 = utf_end(s8));
        TRY(std::advance(i8, 6));
        TEST_EQUAL(u_str(str_insert_in(s8, i8, i8, t8)), u8"€urope");
        TEST_EQUAL(s8, u8"Hello €uropeworld");
        s8 = u8"Hello world";
        TRY(i8 = utf_begin(s8));
        TRY(j8 = utf_end(s8));
        TRY(std::advance(i8, 6));
        TEST_EQUAL(u_str(str_insert_in(s8, irange(i8, i8), utf_range(t8))), u8"€urope");
        TEST_EQUAL(s8, u8"Hello €uropeworld");
        s8 = u8"Hello world";
        TEST_EQUAL(u_str(str_insert_in(s8, utf_range(s8), t8)), u8"€urope");
        TEST_EQUAL(s8, u8"€urope");
        s8 = u8"Hello world";
        TEST_EQUAL(u_str(str_insert_in(s8, utf_range(s8), utf_range(t8))), u8"€urope");
        TEST_EQUAL(s8, u8"€urope");

        s16 = u"Hello world";
        t16 = u"€urope";
        TRY(i16 = j16 = utf_begin(s16));
        TRY(std::advance(j16, 5));
        TEST_EQUAL(str_insert(i16, j16, t16), u"€urope world");
        TEST_EQUAL(str_insert(irange(i16, j16), utf_range(t16)), u"€urope world");
        TRY(i16 = utf_begin(s16));
        TRY(j16 = utf_end(s16));
        TRY(std::advance(i16, 6));
        TEST_EQUAL(str_insert(i16, j16, t16), u"Hello €urope");
        TEST_EQUAL(str_insert(irange(i16, j16), utf_range(t16)), u"Hello €urope");
        TEST_EQUAL(str_insert(i16, i16, t16), u"Hello €uropeworld");
        TEST_EQUAL(str_insert(irange(i16, i16), utf_range(t16)), u"Hello €uropeworld");
        TEST_EQUAL(str_insert(utf_range(s16), t16), u"€urope");
        TEST_EQUAL(str_insert(utf_range(s16), utf_range(t16)), u"€urope");
        s16 = u"Hello world";
        TRY(i16 = j16 = utf_begin(s16));
        TRY(std::advance(j16, 5));
        TEST_EQUAL(u_str(str_insert_in(s16, i16, j16, t16)), u"€urope");
        TEST_EQUAL(s16, u"€urope world");
        s16 = u"Hello world";
        TRY(i16 = j16 = utf_begin(s16));
        TRY(std::advance(j16, 5));
        TEST_EQUAL(u_str(str_insert_in(s16, irange(i16, j16), utf_range(t16))), u"€urope");
        TEST_EQUAL(s16, u"€urope world");
        s16 = u"Hello world";
        TRY(i16 = utf_begin(s16));
        TRY(j16 = utf_end(s16));
        TRY(std::advance(i16, 6));
        TEST_EQUAL(u_str(str_insert_in(s16, i16, j16, t16)), u"€urope");
        TEST_EQUAL(s16, u"Hello €urope");
        s16 = u"Hello world";
        TRY(i16 = utf_begin(s16));
        TRY(j16 = utf_end(s16));
        TRY(std::advance(i16, 6));
        TEST_EQUAL(u_str(str_insert_in(s16, irange(i16, j16), utf_range(t16))), u"€urope");
        TEST_EQUAL(s16, u"Hello €urope");
        s16 = u"Hello world";
        TRY(i16 = utf_begin(s16));
        TRY(j16 = utf_end(s16));
        TRY(std::advance(i16, 6));
        TEST_EQUAL(u_str(str_insert_in(s16, i16, t16)), u"€urope");
        TEST_EQUAL(s16, u"Hello €uropeworld");
        s16 = u"Hello world";
        TRY(i16 = utf_begin(s16));
        TRY(j16 = utf_end(s16));
        TRY(std::advance(i16, 6));
        TEST_EQUAL(u_str(str_insert_in(s16, i16, i16, t16)), u"€urope");
        TEST_EQUAL(s16, u"Hello €uropeworld");
        s16 = u"Hello world";
        TRY(i16 = utf_begin(s16));
        TRY(j16 = utf_end(s16));
        TRY(std::advance(i16, 6));
        TEST_EQUAL(u_str(str_insert_in(s16, irange(i16, i16), utf_range(t16))), u"€urope");
        TEST_EQUAL(s16, u"Hello €uropeworld");
        s16 = u"Hello world";
        TEST_EQUAL(u_str(str_insert_in(s16, utf_range(s16), t16)), u"€urope");
        TEST_EQUAL(s16, u"€urope");
        s16 = u"Hello world";
        TEST_EQUAL(u_str(str_insert_in(s16, utf_range(s16), utf_range(t16))), u"€urope");
        TEST_EQUAL(s16, u"€urope");

        s32 = U"Hello world";
        t32 = U"€urope";
        TRY(i32 = j32 = utf_begin(s32));
        TRY(std::advance(j32, 5));
        TEST_EQUAL(str_insert(i32, j32, t32), U"€urope world");
        TEST_EQUAL(str_insert(irange(i32, j32), utf_range(t32)), U"€urope world");
        TRY(i32 = utf_begin(s32));
        TRY(j32 = utf_end(s32));
        TRY(std::advance(i32, 6));
        TEST_EQUAL(str_insert(i32, j32, t32), U"Hello €urope");
        TEST_EQUAL(str_insert(irange(i32, j32), utf_range(t32)), U"Hello €urope");
        TEST_EQUAL(str_insert(i32, i32, t32), U"Hello €uropeworld");
        TEST_EQUAL(str_insert(irange(i32, i32), utf_range(t32)), U"Hello €uropeworld");
        TEST_EQUAL(str_insert(utf_range(s32), t32), U"€urope");
        TEST_EQUAL(str_insert(utf_range(s32), utf_range(t32)), U"€urope");
        s32 = U"Hello world";
        TRY(i32 = j32 = utf_begin(s32));
        TRY(std::advance(j32, 5));
        TEST_EQUAL(u_str(str_insert_in(s32, i32, j32, t32)), U"€urope");
        TEST_EQUAL(s32, U"€urope world");
        s32 = U"Hello world";
        TRY(i32 = j32 = utf_begin(s32));
        TRY(std::advance(j32, 5));
        TEST_EQUAL(u_str(str_insert_in(s32, irange(i32, j32), utf_range(t32))), U"€urope");
        TEST_EQUAL(s32, U"€urope world");
        s32 = U"Hello world";
        TRY(i32 = utf_begin(s32));
        TRY(j32 = utf_end(s32));
        TRY(std::advance(i32, 6));
        TEST_EQUAL(u_str(str_insert_in(s32, i32, j32, t32)), U"€urope");
        TEST_EQUAL(s32, U"Hello €urope");
        s32 = U"Hello world";
        TRY(i32 = utf_begin(s32));
        TRY(j32 = utf_end(s32));
        TRY(std::advance(i32, 6));
        TEST_EQUAL(u_str(str_insert_in(s32, irange(i32, j32), utf_range(t32))), U"€urope");
        TEST_EQUAL(s32, U"Hello €urope");
        s32 = U"Hello world";
        TRY(i32 = utf_begin(s32));
        TRY(j32 = utf_end(s32));
        TRY(std::advance(i32, 6));
        TEST_EQUAL(u_str(str_insert_in(s32, i32, t32)), U"€urope");
        TEST_EQUAL(s32, U"Hello €uropeworld");
        s32 = U"Hello world";
        TRY(i32 = utf_begin(s32));
        TRY(j32 = utf_end(s32));
        TRY(std::advance(i32, 6));
        TEST_EQUAL(u_str(str_insert_in(s32, i32, i32, t32)), U"€urope");
        TEST_EQUAL(s32, U"Hello €uropeworld");
        s32 = U"Hello world";
        TRY(i32 = utf_begin(s32));
        TRY(j32 = utf_end(s32));
        TRY(std::advance(i32, 6));
        TEST_EQUAL(u_str(str_insert_in(s32, irange(i32, i32), utf_range(t32))), U"€urope");
        TEST_EQUAL(s32, U"Hello €uropeworld");
        s32 = U"Hello world";
        TEST_EQUAL(u_str(str_insert_in(s32, utf_range(s32), t32)), U"€urope");
        TEST_EQUAL(s32, U"€urope");
        s32 = U"Hello world";
        TEST_EQUAL(u_str(str_insert_in(s32, utf_range(s32), utf_range(t32))), U"€urope");
        TEST_EQUAL(s32, U"€urope");

    }

    void check_join() {

        vector<u8string> v8;
        vector<u16string> v16;
        vector<u32string> v32;

        v8.clear();                      TEST_EQUAL(str_join(v8), "");
        v8 = {"Hello"};                  TEST_EQUAL(str_join(v8), "Hello");
        v8 = {"Hello","world"};          TEST_EQUAL(str_join(v8), "Helloworld");
        v8 = {"Hello","world","again"};  TEST_EQUAL(str_join(v8), "Helloworldagain");
        v8.clear();                      TEST_EQUAL(str_join(v8, " "), "");
        v8 = {"Hello"};                  TEST_EQUAL(str_join(v8, " "), "Hello");
        v8 = {"Hello","world"};          TEST_EQUAL(str_join(v8, " "), "Hello world");
        v8 = {"Hello","world","again"};  TEST_EQUAL(str_join(v8, " "), "Hello world again");
        v8.clear();                      TEST_EQUAL(str_join(v8, "<*>"s), "");
        v8 = {"Hello"};                  TEST_EQUAL(str_join(v8, "<*>"s), "Hello");
        v8 = {"Hello","world"};          TEST_EQUAL(str_join(v8, "<*>"s), "Hello<*>world");
        v8 = {"Hello","world","again"};  TEST_EQUAL(str_join(v8, "<*>"s), "Hello<*>world<*>again");

        v16.clear();                         TEST_EQUAL(str_join(v16), u"");
        v16 = {u"Hello"};                    TEST_EQUAL(str_join(v16), u"Hello");
        v16 = {u"Hello",u"world"};           TEST_EQUAL(str_join(v16), u"Helloworld");
        v16 = {u"Hello",u"world",u"again"};  TEST_EQUAL(str_join(v16), u"Helloworldagain");
        v16.clear();                         TEST_EQUAL(str_join(v16, u" "), u"");
        v16 = {u"Hello"};                    TEST_EQUAL(str_join(v16, u" "), u"Hello");
        v16 = {u"Hello",u"world"};           TEST_EQUAL(str_join(v16, u" "), u"Hello world");
        v16 = {u"Hello",u"world",u"again"};  TEST_EQUAL(str_join(v16, u" "), u"Hello world again");
        v16.clear();                         TEST_EQUAL(str_join(v16, u"<*>"s), u"");
        v16 = {u"Hello"};                    TEST_EQUAL(str_join(v16, u"<*>"s), u"Hello");
        v16 = {u"Hello",u"world"};           TEST_EQUAL(str_join(v16, u"<*>"s), u"Hello<*>world");
        v16 = {u"Hello",u"world",u"again"};  TEST_EQUAL(str_join(v16, u"<*>"s), u"Hello<*>world<*>again");

        v32.clear();                         TEST_EQUAL(str_join(v32), U"");
        v32 = {U"Hello"};                    TEST_EQUAL(str_join(v32), U"Hello");
        v32 = {U"Hello",U"world"};           TEST_EQUAL(str_join(v32), U"Helloworld");
        v32 = {U"Hello",U"world",U"again"};  TEST_EQUAL(str_join(v32), U"Helloworldagain");
        v32.clear();                         TEST_EQUAL(str_join(v32, U" "), U"");
        v32 = {U"Hello"};                    TEST_EQUAL(str_join(v32, U" "), U"Hello");
        v32 = {U"Hello",U"world"};           TEST_EQUAL(str_join(v32, U" "), U"Hello world");
        v32 = {U"Hello",U"world",U"again"};  TEST_EQUAL(str_join(v32, U" "), U"Hello world again");
        v32.clear();                         TEST_EQUAL(str_join(v32, U"<*>"s), U"");
        v32 = {U"Hello"};                    TEST_EQUAL(str_join(v32, U"<*>"s), U"Hello");
        v32 = {U"Hello",U"world"};           TEST_EQUAL(str_join(v32, U"<*>"s), U"Hello<*>world");
        v32 = {U"Hello",U"world",U"again"};  TEST_EQUAL(str_join(v32, U"<*>"s), U"Hello<*>world<*>again");

    }

}

TEST_MODULE(unicorn, string_manipulation_f_m) {

    check_fix_left();
    check_fix_right();
    check_insert();
    check_join();

}
