#!/usr/bin/env bash

ucdroot=http://www.unicode.org/Public/UCD/latest/ucd
rm -rf ucd UCD.zip Unihan.zip
mkdir ucd
curl -O $ucdroot/UCD.zip
curl -O $ucdroot/Unihan.zip
unzip UCD.zip -d ucd
unzip Unihan.zip -d ucd
rm -f UCD.zip Unihan.zip
