#!/usr/bin/env bash

if ! [ "$(ls */*.md 2>/dev/null)" ]; then exit; fi

title=$(cat */*.md | head -n 1 | sed -E 's/^# \[(.+)\].+$/\1/')

cat << EOF
# $title #

## Index ##

EOF

for md in */*.md; do
    path=${md%.*}
    name=${path#*/}
    subtitle=$(head -n 1 $md | sed -E 's/^# .+: (.+) #$/\1/')
    # [Skeleton Library](index.html): Core Definitions #
    echo "* [$path.hpp]($name.html) -- $subtitle"
done
